In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)
sales_data = np.random.randint(1000, 5001, size=(12, 4))
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
categories = ["Electronics", "Clothing", "Home & Kitchen", "Sports"]

sales_df = pd.DataFrame(sales_data, columns=categories, index=months)
print(sales_df)


     Electronics  Clothing  Home & Kitchen  Sports
Jan         4174      4507            1860    2294
Feb         2130      2095            4772    4092
Mar         2638      3169            1466    2238
Apr         1330      2482            3135    4444
May         4171      3919            4735    1130
Jun         2685      4380            1769    3391
Jul         2515      4485            3853    3433
Aug         2215      1955            3324    2184
Sep         1459      4385            1021    3300
Oct         1747      3904            4632    1474
Nov         2082      3558            4753    3047
Dec         4547      3747            1975    2806


In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)
sales_data = np.random.randint(1000, 5001, size=(12, 4))
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
categories = ["Electronics", "Clothing", "Home & Kitchen", "Sports"]

sales_df = pd.DataFrame(sales_data, columns=categories, index=months)

print(sales_df.head())
print(sales_df.describe())
sales_per_category = sales_df.sum()
sales_df["Total Sales"] = sales_df.sum(axis=1)
sales_growth = sales_df.diff().mean()

sales_df["Growth Rate"] = sales_df["Total Sales"].pct_change() * 100

def apply_discount(df, roll_number):
    if roll_number % 2 == 0:
        df["Electronics"] *= 0.9  
    else:
        df["Clothing"] *= 0.85  
    return df
roll_number = 24  
sales_df = apply_discount(sales_df, roll_number)

print(sales_df)


     Electronics  Clothing  Home & Kitchen  Sports
Jan         4174      4507            1860    2294
Feb         2130      2095            4772    4092
Mar         2638      3169            1466    2238
Apr         1330      2482            3135    4444
May         4171      3919            4735    1130
       Electronics     Clothing  Home & Kitchen       Sports
count    12.000000    12.000000       12.000000    12.000000
mean   2641.083333  3548.833333     3107.916667  2819.416667
std    1087.608089   925.564578     1437.576335   996.676428
min    1330.000000  1955.000000     1021.000000  1130.000000
25%    1998.250000  2997.250000     1837.250000  2224.500000
50%    2365.000000  3825.500000     3229.500000  2926.500000
75%    3056.500000  4381.250000     4657.750000  3401.500000
max    4547.000000  4507.000000     4772.000000  4444.000000
     Electronics  Clothing  Home & Kitchen  Sports  Total Sales  Growth Rate
Jan       3756.6      4507            1860    2294        12835     

In [4]:
plt.figure(figsize=(10, 6))
for category in categories:
    plt.plot(sales_df.index, sales_df[category], marker='o', label=category)
plt.xlabel("Month")
plt.ylabel("Sales")
plt.title("Monthly Sales Trends")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(data=sales_df[categories])
plt.title("Sales Distribution per Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

print(sales_df)


NameError: name 'plt' is not defined

In [5]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
absolute_values = np.abs(array)
print("Absolute Values:\n", absolute_values)

flattened_percentiles = np.percentile(array, [25, 50, 75])
column_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print("Flattened Percentiles:\n", flattened_percentiles)
print("Column-wise Percentiles:\n", column_percentiles)
print("Row-wise Percentiles:\n", row_percentiles)

mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Flattened - Mean:", mean_flattened, "Median:", median_flattened, "Std Dev:", std_flattened)
print("Column-wise - Mean:", mean_columns, "Median:", median_columns, "Std Dev:", std_columns)
print("Row-wise - Mean:", mean_rows, "Median:", median_rows, "Std Dev:", std_rows)

print(sales_df)


Absolute Values:
 [[1 2 3]
 [4 5 6]]
Flattened Percentiles:
 [-3.5 -0.5  2.5]
Column-wise Percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise Percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened - Mean: -0.5 Median: -0.5 Std Dev: 3.8622100754188224
Column-wise - Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std Dev: [2.5 3.5 4.5]
Row-wise - Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std Dev: [2.05480467 4.78423336]
     Electronics  Clothing  Home & Kitchen  Sports  Total Sales  Growth Rate
Jan       3756.6      4507            1860    2294        12835          NaN
Feb       1917.0      2095            4772    4092        13089     1.978964
Mar       2374.2      3169            1466    2238         9511   -27.335931
Apr       1197.0      2482            3135    4444        11391    19.766586
May       3753.9      3919            4735    1130        13955    22.508998
Jun       2416.5      4380            1769    3391        12225 

In [6]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Floor Values:", floor_values)
print("Ceiling Values:", ceiling_values)
print("Truncated Values:", truncated_values)
print("Rounded Values:", rounded_values)

def swap_list_elements(lst, idx1, idx2):
    temp = lst[idx1]
    lst[idx1] = lst[idx2]
    lst[idx2] = temp
    return lst
my_list = [1, 2, 3, 4, 5]
swapped_list = swap_list_elements(my_list, 1, 3)
print("Swapped List:", swapped_list)

def swap_set_elements(s, elem1, elem2):
    lst = list(s)
    if elem1 in lst and elem2 in lst:
        idx1, idx2 = lst.index(elem1), lst.index(elem2)
        lst[idx1], lst[idx2] = lst[idx2], lst[idx1]
        return set(lst)
    return s

my_set = {10, 20, 30, 40, 50}
swapped_set = swap_set_elements(my_set, 20, 40)
print("Swapped Set:", swapped_set)
print(sales_df)


Floor Values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling Values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values: [-2. -2. -0.  0.  2.  2.  3.]
Swapped List: [1, 4, 3, 2, 5]
Swapped Set: {40, 10, 50, 20, 30}
     Electronics  Clothing  Home & Kitchen  Sports  Total Sales  Growth Rate
Jan       3756.6      4507            1860    2294        12835          NaN
Feb       1917.0      2095            4772    4092        13089     1.978964
Mar       2374.2      3169            1466    2238         9511   -27.335931
Apr       1197.0      2482            3135    4444        11391    19.766586
May       3753.9      3919            4735    1130        13955    22.508998
Jun       2416.5      4380            1769    3391        12225   -12.396990
Jul       2263.5      4485            3853    3433        14286    16.858896
Aug       1993.5      1955            3324    2184         9678   -32.255355
Sep       1313.1      4385            1021    3300        1